# Copyright (c)  2025  Xiaomi Corporation
name: build

on:
  push:
    branches:
      - master
      - silero-vad

  pull_request:
    branches:
      - master

  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.10"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.os }}

      - name: Install mlx
        shell: bash
        run: |
          python3 -m pip install mlx==0.26.3

      - name: Show mlx
        shell: bash
        run: |
          python3 -m mlx --cmake-dir
          echo "---"
          ls -lh $(python3 -m mlx --cmake-dir)/lib
          echo "---"
          ls -lh $(python3 -m mlx --cmake-dir)/include/
          echo "---"
          ls -lh $(python3 -m mlx --cmake-dir)/include/mlx

      - name: Build
        shell: bash
        run: |
          export CMAKE_CXX_COMPILER_LAUNCHER=ccache
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          cmake --version

          export MLX_CMAKE_DIR=$(python3 -m mlx --cmake-dir)

          mkdir build
          cd build
          cmake ..
          make VERBOSE=1

          ls -lh bin
          echo "---"
          ls -lh lib

      - name: View dependencies (ubuntu-latest)
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          cd build/bin
          readelf -d sherpa-mlx-vad
          echo "---"
          ldd sherpa-mlx-vad

      - name: View dependencies (macos-latest)
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          cd build/bin
          otool -L sherpa-mlx-vad
          echo "---"
          otool -l sherpa-mlx-vad

      - name: Collect results
        shell: bash
        run: |
          mv build/bin .
          tar cjfv bin.tar.bz2 bin

      - uses: actions/upload-artifact@v4
        with:
          name: bin-${{ matrix.os }}
          path: ./*.tar.bz2

  test_vad:
    needs: [build]
    name: vad ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.10"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install mlx
        shell: bash
        run: |
          python3 -m pip install mlx==0.26.3

      - name: Retrieve artifact from ${{ matrix.os }}
        uses: actions/download-artifact@v4
        with:
          name: bin-${{ matrix.os }}
          path: /tmp/build

      - name: Show bin
        shell: bash
        run: |
          cd /tmp/build
          ls -lh
          tar xvf bin.tar.bz2
          ls -lh bin
