# Copyright (c)  2025  Xiaomi Corporation
name: style_check

on:
  push:
    branches:
      - master
      - ci
    paths:
      - '.github/workflows/style_check.yaml'
      - 'sherpa-mlx/**'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/style_check.yaml'
      - 'sherpa-mlx/**'
  workflow_dispatch:

concurrency:
  group: style_check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  style_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check style with cpplint
        shell: bash
        working-directory: ${{github.workspace}}
        run: ./scripts/check_style_cpplint.sh
